//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWAssignmentPrj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderid { get; set; }
        public string productName { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public Nullable<System.DateTime> shipdate { get; set; }
        public int quantity { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
